project:
  type: website
  output-dir: docs

website:
  title: "Matthieu Hanf"
  site-url: https://www.quantumjitter.com
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - software.qmd
    right:
      - icon: github
        href: https://github.com/mhanf
        
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) | Hosted by [Github](https://www.github.com)"
    right: "© 2023 [Matthieu Hanf](/about) | [MIT License](https://opensource.org/license/mit-0/)"
      
format:
  html:
    theme: journal
    css: styles.css
    toc: true


