project:
  type: website
  output-dir: docs

execute:
  freeze: true

website:
  title: "> M|H"
  site-url: mhanf.github.io/quarto_website/
  description: Personal website
  repo-url: https://github.com/mhanf/quarto_website
  repo-actions: issue
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: software.qmd
        text: Project
    right:
      - icon: github
        href: https://github.com/mhanf
        
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) | Hosted by [Github](https://www.github.com)"
    right: "© 2023 Matthieu Hanf | [MIT License](https://opensource.org/license/mit-0/)"
      
format:
  html:
    theme:
      light: theme/light_theme.scss
      dark: theme/dark_theme.scss
    smooth-scroll: true
    link-external-newwindow: true


